### ISSUE TITLE
android 8，背景颜色错误

### ISSUE THREAD

**Issue by bwyun** [zfdang/zSMTH-Android#10]
在设置中配色模式选择黑色背景。十大和收藏的首页为正确的黑背景白字体。但进入版面，即版面内文章列表页则变为白色背景黑色字体。重装等均无法恢复正常。

**Comment by zfdang** [comment]
这个貌似是google的一个bug，对night mode支持的有问题，这么多年一直没有完全fix:

https://issuetracker.google.com/issues/37083803

**Comment by zfdang** [comment]
1.7.7版本解决这个问题了
