### ISSUE TITLE
有了新版本后，旧版本没有提示升级。

### ISSUE THREAD

**Issue by iLibra** [zfdang/zSMTH-Android#11]
而且各大应用商店里能下载到的最新版还是160

**Comment by zfdang** [comment]
需要手动更新，不愿意升的不会被骚扰。只上架了google和腾讯的应用商店，其他的应该是其他人上载的

**Comment by iLibra** [comment]
更新可以手动 但是起码应该用个红点提示下有新版本。
不然怎么想的起来检查更新。
至于怕骚扰用户的问题 不要用弹出窗口。仅仅是在设置上显示个红点。或者每个新版本仅提示一次。
这些都是很常规的交互设计。

另外不想再提新issue就在这里说
首页导读下面版面中文名字前面都带了个英文名。建议去掉。
那个英文对用户没有任何信息量。而且让版面视觉效果显得杂乱。
同时建议调整下 标题和版面名的行间距。
目前整体视觉留白太少。一看就是工程师兼职美工的成果^O^

**Comment by iLibra** [comment]
另外在版面内部的帖子列表界面

每个帖子的标题，作者名，回复 这三行前面的左边距居然全不一样。这里应该还是需要对齐下 更好看

**Comment by iLibra** [comment]
@zfdang 建议有可能的话 参考下谷歌material design的guideline里面有关于行间距 边距的常见建议值。用那些值 都是经过考验的。不容易翻车。
