### ISSUE TITLE
如文章内容中含"<" 符号，内容会显示不全

### ISSUE THREAD

**Issue by DazzyWalkman** [zfdang/zSMTH-Android#20]
如题，1.8.3（760）版本。不全情况请见附图。请恕我借微水木展示同一帖子内容作对比。
![Screenshot_20200327-113934](https://user-images.githubusercontent.com/20811819/77719846-47429900-7021-11ea-939e-8e5ddf337409.jpg)
![Screenshot_20200327-113737_1](https://user-images.githubusercontent.com/20811819/77719861-4f9ad400-7021-11ea-8ecb-6f41876d8cd5.jpg)
![Screenshot_20200327-113721_1](https://user-images.githubusercontent.com/20811819/77719867-54f81e80-7021-11ea-94fc-ba3dddccbfee.jpg)

**Comment by zfdang** [comment]
fixed
