### ISSUE TITLE
Google play更新后无法使用

### ISSUE THREAD

**Issue by libralibra** [zfdang/zSMTH-Android#23]
今天更新1.8.4后无法使用，截图如下
![Screenshot_2020-06-28-08-50-33-140_com zfdang zsmth_android](https://user-images.githubusercontent.com/875627/85941766-c5faeb00-b91c-11ea-8810-a15f78f51c5b.jpg)

**Comment by zfdang** [comment]
这个上传的果然有问题，已经更新apk了，等play通过了你再升级一次吧

**Comment by libralibra** [comment]
多谢回复，再次更新后好了。
