### ISSUE TITLE
如何动态修改长按弹出的菜单

### ISSUE THREAD

**Issue by openmartin** [zfdang/zSMTH-Android#24]
开发者你好，我是水木的一名版主，我修改了一下zsmth满足我日常管理板块的需求

增加了同主题删除和封ID的功能
https://github.com/openmartin/zSMTH-Android

我想把我的代码合并到主分支上去，普通用户和版主的菜单是不一样，但是不知道怎么动态的修改长按弹出的菜单

**Comment by openmartin** [comment]
我是写java后台的，android不熟，希望开发者您给个思路，感谢🙏

**Comment by zfdang** [comment]
程序里怎么判断当前用户是不是这个版的版主呢？我建议直接把这些菜单加进去，加个备注,比如 "同主题删除(版主专用)“。反正普通人用了也会失败，没啥坏处

**Comment by openmartin** [comment]
拖延症，开发好了，麻烦抽时间 review 一下

#26

**Comment by zfdang** [comment]
merge进去了，感谢！
