### ISSUE TITLE
v1.8.6(801)登录提示验证码错误

### ISSUE THREAD

**Issue by xjtuecho** [zfdang/zSMTH-Android#27]
![20200808071341](https://user-images.githubusercontent.com/1918299/89695489-be305c80-d946-11ea-95a8-d234b1fc4f29.jpg)

看起来是网站加了验证码登录认证？

**Comment by shijin1984** [comment]
+1

**Comment by openmartin** [comment]
据了解是因为深受广告机器人的苦扰，所以加了腾讯验证码，不知道在手机上第三方app有何实现方法

**Comment by zfdang** [comment]
更新了

**Comment by shijin1984** [comment]
感谢及时更新！

app登录时转到web，如果在里面选了**保存一月**，并不起作用，下次打开app时一般又要重新登录。

这个问题是属于bug还是难以实现的feature?

**Comment by zfdang** [comment]
更新一下吧



---原始邮件---
发件人: "shijin1984"<notifications@github.com&gt;
发送时间: 2020年8月12日(周三) 下午4:37
收件人: "zfdang/zSMTH-Android"<zSMTH-Android@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Zhengfa Dang"<dantifer@gmail.com&gt;;
主题: Re: [zfdang/zSMTH-Android] v1.8.6(801)登录提示验证码错误 (#27)




 
感谢及时更新！
 
app登录时转到web，如果在里面选了保存一月，并不起作用，下次打开app时一般又要重新登录。
 
这个问题是属于bug还是难以实现的feature?

**Comment by xjtuecho** [comment]
看最新版用发布日期作为版本号了，建议去掉一个20，比如最新的v20.8.12就够啦，因为软件和他的用户活到21xx年可能性都不大。
