### ISSUE TITLE
登陆状态无法保存

### ISSUE THREAD

**Issue by crazyxhz** [zfdang/zSMTH-Android#32]
登陆成功之后，长时间后台再切回，需要重新登陆一遍才能访问需要登陆的板块

**Comment by zfdang** [comment]
登录超时的问题没法彻底解决，除非后台一直连接着水木。您先更新到最新版本，看看有没有好转吧

**Comment by crazyxhz** [comment]
> 登录超时的问题没法彻底解决，除非后台一直连接着水木。您先更新到最新版本，看看有没有好转吧

iOS上的最水木 就不用重新登陆 https://github.com/atone/iZSM，也许可以参考下？ zSMTH是安卓上最好用的客户端了，大佬再努把力，解决了登陆问题就完美了
