### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by 025nju** [zfdang/zSMTH-Android#33]
看了作者的blog愣是没找到邮箱。不算issue，改进建议吧希望能看到。
感受的优点：
1）加载速度和用过的其他水木客户端相比能明显感到更快。
2）功能更多。
不足：
1）标题底下显示的板块名称，橙色太亮了，有点distractive.
2）浏览帖子时，appbar的导航导同板块主题图表的图表，对新用户比较困惑，是否可以换成文字“本版”或者别的。
3）浏览帖子时，内容里“引用原文”部分是青色，和问题1)一样。
4）分页能否改成增量显示，比如点下一页，不要让之前的消失，而是往下追加多显示1页。更符合大多app给用户养成的习惯，而且时不时需要回看上面某楼，会更方便。

暂时就这么多。感谢作者！

**Comment by zfdang** [comment]
调整了一下颜色，你可以试试看新版的
