### ISSUE TITLE
是否可将smth网址放到设置项中？

### ISSUE THREAD

**Issue by xjtuecho** [zfdang/zSMTH-Android#35]
这次水木DNS出问题，zSMTH打开困难，PC上改一下Hosts文件，将bbs.newsmth.net指向实际的IP就可以了。
Android手机上改起来很麻烦，如果把网址放到设置项中就比较方便了。
KCN给出的水木社区目前临时访问地址：
```
pc: www.mysmth.net
wap: wap.mysmth.net
term: bbs.mysmth.net
```

**Comment by openmartin** [comment]
https://github.com/zfdang/zSMTH-Android/blob/f25e56e93a47152776510febc4a413c78cf13b9d/app/src/main/java/com/zfdang/zsmth_android/newsmth/SMTHHelper.java#L75

这一行代码改一下应该就行了

**Comment by skyformat99** [comment]
谁帮忙编译个最新版的apk啊？

**Comment by xjtuecho** [comment]
https://github.com/vinneyg/zSMTH-Android-Vinney.git
这个版本已经把smth网址放到设置项中了，试了下工作良好。

**Comment by skyformat99** [comment]
> https://github.com/vinneyg/zSMTH-Android-Vinney.git
> 这个版本已经把smth网址放到设置项中了，试了下工作良好。

这个版本改了很多；
操作习惯和zfdang的不一样了
单击容易进入编辑状态
刷新机制也不一样

**Comment by zfdang** [comment]
刚刚改了code, 一会儿去actions里自动编译那里下载apk就好了

**Comment by zfdang** [comment]
https://github.com/zfdang/zSMTH-Android/releases/tag/tag-864

**Comment by xjtuecho** [comment]
> > https://github.com/vinneyg/zSMTH-Android-Vinney.git
> > 这个版本已经把smth网址放到设置项中了，试了下工作良好。
> 
> 这个版本改了很多；
> 操作习惯和zfdang的不一样了
> 单击容易进入编辑状态
> 刷新机制也不一样

这个版本用了下，貌似还挺好用
