### ISSUE TITLE
最近总是链接不了

### ISSUE THREAD

**Issue by skyformat99** [zfdang/zSMTH-Android#37]
最新版本，909版本
总是断
然后再也链接不了

**Comment by zfdang** [comment]
啥叫总是断？无法打开帖子么？

**Comment by skyformat99** [comment]
网站都连接不上； 特别是早上，晚上。
不知道有没有其他人遇到过。然后打开 浏览器，也是，说什么ip访问过多，屏蔽了

**Comment by zfdang** [comment]
那估计是你自己网络的问题

**Comment by skyformat99** [comment]
> 那估计是你自己网络的问题

应该不是，十来年水木每天都上
又不是一天两天
最近才出现，而且WiFi也好，4g也好，都出现

**Comment by skyformat99** [comment]
![IMG_20210712_182113](https://user-images.githubusercontent.com/10938976/125272089-08cc0d00-e33e-11eb-86a8-45b9d1064916.jpg)

**Comment by skyformat99** [comment]
就是这个图片情况
