### ISSUE TITLE
登录时返回验证码是怎么回事

### ISSUE THREAD

**Issue by huangchen007** [zfdang/zSMTH-Android#39]
![Screenshot_2022-04-22-10-52-24-458_com zfdang zsmth_android](https://user-images.githubusercontent.com/6696381/164587165-96d9c21f-3806-43c8-ab3e-ddcb4b0c1d3e.jpg)

版本21.11.07 （912）

**Comment by skyformat99** [comment]
没戏了，最新的登录不了

**Comment by skyformat99** [comment]
作者呢
忙活啥子

**Comment by shijin1984** [comment]
+1

催更

**Comment by zfdang** [comment]
适配了新的登录方法，更新一下吧

**Comment by shijin1984** [comment]
大佬，play store上也推一下新版本啊!

**Comment by zfdang** [comment]
play store更新被拒绝了，说UGC的内容要提供举报的功能... 

我无语了

**Comment by shijin1984** [comment]
同无语...

Zhengfa Dang ***@***.***> 于 2022年4月25日周一 下午8:33写道：
