### ISSUE TITLE
没有历史回复查看功能

### ISSUE THREAD

**Issue by ghost** [zfdang/zSMTH-Android#4]
回复阅读之后没法再查看

**Comment by zfdang** [comment]
需要手动刷新，才能看到自己的帖子

On Sun, Sep 04, 2016 at 8:23 AM, delavior < notifications@github.com [notifications@github.com] > wrote:
回复阅读之后没法再查看

**Comment by delavior** [comment]
抱歉，没有说清楚，不是帖子本身，是别人回复我的提醒消息，如图
![screenshot_2016-09-08-20-54-26](https://cloud.githubusercontent.com/assets/5194970/18350303/d4b03bfc-7607-11e6-8eab-7a2d6bd8a825.png)
这种回复阅读完之后，回到其他界面之后，再想返回阅读就不可能了，能否调整一下？

**Comment by zfdang** [comment]
这个功能应该有了
