### ISSUE TITLE
建议2个域名都支持啊

### ISSUE THREAD

**Issue by skyformat99** [zfdang/zSMTH-Android#45]
newsmth
mysmth
最好两个都支持啊；要不然今天又登录不上了啊。。。。

啊啊啊啊啊啊啊啊啊啊啊

**Comment by zfdang** [comment]
改了一下域名，更新一下试试看吧

**Comment by skyformat99** [comment]
> 改了一下域名，更新一下试试看吧

完全不行啊；配置里面留一个地方，让用户自己修改不就得了
