### ISSUE TITLE
Serious MaintainUserStatusWorker leak

### ISSUE THREAD

**Issue by RuralHunter** [zfdang/zSMTH-Android#50]
Workers are persistent even android device is rebooted. MaintainUserStatusWorker is scheduled by every calls of onCreate() in [MainActivity](https://github.com/zfdang/zSMTH-Android/blob/b0f1d7b1fed98580245c0b2f33eee017db0b0771/app/src/main/java/com/zfdang/zsmth_android/MainActivity.java#L191). This could result many many instances of MaintainUserStatusWorker running in background.
Fix is here: https://github.com/RuralHunter/zSMTH-Android/commit/f3ebdc04a04145e70bf787be21246d971c26fbf4

**Comment by zfdang** [comment]
will you please add one Pull Request?

**Comment by skyformat99** [comment]
赶紧合并啊，大牛牛们
