### ISSUE TITLE
可以适配小米 mix2么

### ISSUE THREAD

**Issue by sth4nth** [zfdang/zSMTH-Android#8]
全面屏上没有适配，有黑边

**Comment by zfdang** [comment]
我不用这型号，只能等有mix2的同学去适配了

**Comment by sth4nth** [comment]
那能不能提示一下改哪，我来试试

**Comment by zfdang** [comment]
你试试这个版本看行不行吧？

http://zsmth-android.zfdang.com/zSMTH-release-v1.7.5.apk

**Comment by sth4nth** [comment]
试了最新版，已经没问题了。thx
